import csv
import pandas as pd

related_topics = [
    ("Physics", "Quantum Mechanics"),
    ("Physics", "Thermodynamics"),
    ("Physics", "Relativity"),
    ("Physics", "Particle Physics"),
    ("Physics", "Astrophysics"),
    ("Mathematics", "Algebra"),
    ("Mathematics", "Calculus"),
    ("Mathematics", "Statistics"),
    ("Mathematics", "Number Theory"),
    ("Mathematics", "Topology"),
    ("Biology", "Genetics"),
    ("Biology", "Ecology"),
    ("Biology", "Microbiology"),
    ("Biology", "Botany"),
    ("Biology", "Zoology"),
    ("Chemistry", "Organic Chemistry"),
    ("Chemistry", "Inorganic Chemistry"),
    ("Chemistry", "Analytical Chemistry"),
    ("Chemistry", "Physical Chemistry"),
    ("History", "Modern History"),
    ("History", "Ancient History"),
    ("History", "Medieval History"),
    ("History", "World History"),
    ("Literature", "Poetry"),
    ("Literature", "Drama"),
    ("Literature", "Prose"),
    ("Literature", "Comparative Literature"),
    ("Literature", "Literary Theory"),
    ("Computer Science", "Machine Learning"),
    ("Computer Science", "Data Structures"),
    ("Computer Science", "Algorithms"),
    ("Computer Science", "Cybersecurity"),
    ("Computer Science", "Software Engineering"),
    ("Art", "Painting"),
    ("Art", "Sculpture"),
    ("Art", "Photography"),
    ("Art", "Digital Art"),
    ("Art", "Art History"),
    ("Music", "Classical Music"),
    ("Music", "Jazz"),
    ("Music", "Pop Music"),
    ("Music", "Music Theory"),
    ("Music", "Music Composition"),
    ("Economics", "Macroeconomics"),
    ("Economics", "Microeconomics"),
    ("Economics", "Econometrics"),
    ("Economics", "Development Economics"),
    ("Psychology", "Cognitive Psychology"),
    ("Psychology", "Clinical Psychology"),
    ("Psychology", "Developmental Psychology"),
    ("Psychology", "Social Psychology"),
    ("Sociology", "Urban Sociology"),
    ("Sociology", "Criminology"),
    ("Sociology", "Gender Studies"),
    ("Sociology", "Race and Ethnicity"),
    ("Anthropology", "Cultural Anthropology"),
    ("Anthropology", "Archaeology"),
    ("Anthropology", "Physical Anthropology"),
    ("Anthropology", "Linguistic Anthropology"),
    ("Political Science", "International Relations"),
    ("Political Science", "Comparative Politics"),
    ("Political Science", "Political Theory"),
    ("Political Science", "Public Policy"),
    ("Philosophy", "Ethics"),
    ("Philosophy", "Metaphysics"),
    ("Philosophy", "Epistemology"),
    ("Philosophy", "Logic"),
    ("Philosophy", "Philosophy of Mind"),
    ("Environmental Science", "Climate Change"),
    ("Environmental Science", "Conservation Biology"),
    ("Environmental Science", "Environmental Policy"),
    ("Environmental Science", "Sustainability"),
    ("Geology", "Mineralogy"),
    ("Geology", "Paleontology"),
    ("Geology", "Geophysics"),
    ("Geology", "Volcanology"),
    ("Astronomy", "Stellar Astronomy"),
    ("Astronomy", "Galactic Astronomy"),
    ("Astronomy", "Cosmology"),
    ("Astronomy", "Astrobiology"),
    ("Engineering", "Civil Engineering"),
    ("Engineering", "Mechanical Engineering"),
    ("Engineering", "Electrical Engineering"),
    ("Engineering", "Chemical Engineering"),
    ("Medicine", "Anatomy"),
    ("Medicine", "Physiology"),
    ("Medicine", "Pathology"),
    ("Medicine", "Pharmacology"),
    ("Medicine", "Surgery"),
    ("Law", "Constitutional Law"),
    ("Law", "Criminal Law"),
    ("Law", "Corporate Law"),
    ("Law", "International Law"),
    ("Business", "Marketing"),
    ("Business", "Finance"),
    ("Business", "Management"),
    ("Business", "Entrepreneurship"),
    ("Education", "Curriculum Development"),
    ("Education", "Educational Psychology"),
    ("Education", "Special Education"),
    ("Education", "Educational Leadership"),
    ("Communications", "Journalism"),
    ("Communications", "Public Relations"),
    ("Communications", "Media Studies"),
    ("Communications", "Interpersonal Communication"),
    ("Languages", "Linguistics"),
    ("Languages", "Translation Studies"),
    ("Languages", "Language Acquisition"),
    ("Languages", "Comparative Literature"),
    ("Theater", "Acting"),
    ("Theater", "Directing"),
    ("Theater", "Playwriting"),
    ("Theater", "Stage Design"),
    ("Dance", "Ballet"),
    ("Dance", "Contemporary Dance"),
    ("Dance", "Choreography"),
    ("Dance", "Dance History")
]

# Convert to DataFrame
df_related_topics = pd.DataFrame(related_topics, columns=["Subject", "Related Topic"])

# Save to CSV
df_related_topics.to_csv('related_topics.csv', index=False)
