import csv
import pandas as pd

related_career_aspirations = [
    ("Physics", "Physicist"),
    ("Physics", "Engineer"),
    ("Physics", "Research Scientist"),
    ("Physics", "Astronomer"),
    ("Mathematics", "Mathematician"),
    ("Mathematics", "Data Scientist"),
    ("Mathematics", "Statistician"),
    ("Mathematics", "Operations Research Analyst"),
    ("Biology", "Biologist"),
    ("Biology", "Medical Researcher"),
    ("Biology", "Biotechnologist"),
    ("Biology", "Ecologist"),
    ("Chemistry", "Chemist"),
    ("Chemistry", "Pharmacist"),
    ("Chemistry", "Chemical Engineer"),
    ("Chemistry", "Forensic Scientist"),
    ("History", "Historian"),
    ("History", "Archaeologist"),
    ("History", "Museum Curator"),
    ("History", "Archivist"),
    ("Literature", "Writer"),
    ("Literature", "Editor"),
    ("Literature", "Literary Critic"),
    ("Literature", "Professor"),
    ("Computer Science", "Software Developer"),
    ("Computer Science", "Data Scientist"),
    ("Computer Science", "Cybersecurity Specialist"),
    ("Computer Science", "AI Researcher"),
    ("Art", "Artist"),
    ("Art", "Designer"),
    ("Art", "Art Director"),
    ("Art", "Curator"),
    ("Music", "Musician"),
    ("Music", "Composer"),
    ("Music", "Music Producer"),
    ("Music", "Music Teacher"),
    ("Economics", "Economist"),
    ("Economics", "Financial Analyst"),
    ("Economics", "Policy Analyst"),
    ("Economics", "Consultant"),
    ("Psychology", "Clinical Psychologist"),
    ("Psychology", "Counselor"),
    ("Psychology", "Research Psychologist"),
    ("Psychology", "School Psychologist"),
    ("Sociology", "Sociologist"),
    ("Sociology", "Social Worker"),
    ("Sociology", "Criminologist"),
    ("Sociology", "Community Organizer"),
    ("Anthropology", "Anthropologist"),
    ("Anthropology", "Archaeologist"),
    ("Anthropology", "Cultural Resource Manager"),
    ("Anthropology", "Museum Curator"),
    ("Political Science", "Political Scientist"),
    ("Political Science", "Policy Analyst"),
    ("Political Science", "Diplomat"),
    ("Political Science", "Legislative Assistant"),
    ("Philosophy", "Philosopher"),
    ("Philosophy", "Ethicist"),
    ("Philosophy", "Professor"),
    ("Philosophy", "Writer"),
    ("Environmental Science", "Environmental Scientist"),
    ("Environmental Science", "Conservationist"),
    ("Environmental Science", "Environmental Consultant"),
    ("Environmental Science", "Wildlife Biologist"),
    ("Geology", "Geologist"),
    ("Geology", "Hydrologist"),
    ("Geology", "Environmental Consultant"),
    ("Geology", "Seismologist"),
    ("Astronomy", "Astronomer"),
    ("Astronomy", "Astrophysicist"),
    ("Astronomy", "Planetary Scientist"),
    ("Astronomy", "Observatory Technician"),
    ("Engineering", "Civil Engineer"),
    ("Engineering", "Mechanical Engineer"),
    ("Engineering", "Electrical Engineer"),
    ("Engineering", "Biomedical Engineer"),
    ("Medicine", "Doctor"),
    ("Medicine", "Surgeon"),
    ("Medicine", "Nurse"),
    ("Medicine", "Medical Researcher"),
    ("Law", "Lawyer"),
    ("Law", "Judge"),
    ("Law", "Legal Consultant"),
    ("Law", "Public Prosecutor"),
    ("Business", "Marketing Manager"),
    ("Business", "Financial Analyst"),
    ("Business", "Business Consultant"),
    ("Business", "Entrepreneur"),
    ("Education", "Teacher"),
    ("Education", "School Principal"),
    ("Education", "Educational Consultant"),
    ("Education", "Special Education Teacher"),
    ("Communications", "Journalist"),
    ("Communications", "Public Relations Specialist"),
    ("Communications", "Media Analyst"),
    ("Communications", "Communications Director"),
    ("Languages", "Translator"),
    ("Languages", "Interpreter"),
    ("Languages", "Linguist"),
    ("Languages", "Language Teacher"),
    ("Theater", "Actor"),
    ("Theater", "Director"),
    ("Theater", "Playwright"),
    ("Theater", "Stage Manager"),
    ("Dance", "Dancer"),
    ("Dance", "Choreographer"),
    ("Dance", "Dance Instructor"),
    ("Dance", "Dance Therapist")
]

# Convert to DataFrame
df_related_career_aspirations = pd.DataFrame(related_career_aspirations, columns=["Subject", "Career Aspiration"])

# Save to CSV
df_related_career_aspirations.to_csv('related_career_aspirations.csv', index=False)

